[tools]
starship = "latest"

# ag (the silver-searcher) is built from source when specified via mise.
# This would be okay ... if it had limited dependencies and/or actually built
# successfully.
# ag = "latest"

zellij = { version = "latest", os=["linux", "macos"]}
bat = "latest"
eza = "latest"
atuin = "latest"
jq = "latest"
gh = "latest"
tflint = "latest"
neovim = "0.11.5"
